/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RtcConfigurationRequestBuilderRequestsMetadata, type RtcConfigurationRequestBuilder } from './rtcConfiguration/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/stun
 */
export interface StunRequestBuilder extends BaseRequestBuilder<StunRequestBuilder> {
    /**
     * The rtcConfiguration property
     */
    get rtcConfiguration(): RtcConfigurationRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const StunRequestBuilderUriTemplate = "{+baseurl}/api/v1/stun";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StunRequestBuilderNavigationMetadata: Record<Exclude<keyof StunRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    rtcConfiguration: {
        requestsMetadata: RtcConfigurationRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
