/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RTCConfiguration}
 */
// @ts-ignore
export function createRTCConfigurationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRTCConfiguration;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RTCIceServer}
 */
// @ts-ignore
export function createRTCIceServerFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRTCIceServer;
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RTCConfiguration The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRTCConfiguration(rTCConfiguration: Partial<RTCConfiguration> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "iceServers": n => { rTCConfiguration.iceServers = n.getCollectionOfObjectValues<RTCIceServer>(createRTCIceServerFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param RTCIceServer The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRTCIceServer(rTCIceServer: Partial<RTCIceServer> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "credential": n => { rTCIceServer.credential = n.getStringValue(); },
        "urls": n => { rTCIceServer.urls = n.getCollectionOfPrimitiveValues<string>(); },
        "username": n => { rTCIceServer.username = n.getStringValue(); },
    }
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface RTCConfiguration extends AdditionalDataHolder, Parsable {
    /**
     * The iceServers property
     */
    iceServers?: RTCIceServer[] | null;
}
export interface RTCIceServer extends AdditionalDataHolder, Parsable {
    /**
     * The credential property
     */
    credential?: string | null;
    /**
     * The urls property
     */
    urls?: string[] | null;
    /**
     * The username property
     */
    username?: string | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RTCConfiguration The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRTCConfiguration(writer: SerializationWriter, rTCConfiguration: Partial<RTCConfiguration> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rTCConfiguration || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<RTCIceServer>("iceServers", rTCConfiguration.iceServers, serializeRTCIceServer);
    writer.writeAdditionalData(rTCConfiguration.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RTCIceServer The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRTCIceServer(writer: SerializationWriter, rTCIceServer: Partial<RTCIceServer> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!rTCIceServer || isSerializingDerivedType) { return; }
    writer.writeStringValue("credential", rTCIceServer.credential);
    writer.writeCollectionOfPrimitiveValues<string>("urls", rTCIceServer.urls);
    writer.writeStringValue("username", rTCIceServer.username);
    writer.writeAdditionalData(rTCIceServer.additionalData);
}
/* tslint:enable */
/* eslint-enable */
