/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RtcConfigurationRequestBuilderRequestsMetadata, type RtcConfigurationRequestBuilder } from './rtcConfiguration/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/web-rtc
 */
export interface WebRtcRequestBuilder extends BaseRequestBuilder<WebRtcRequestBuilder> {
    /**
     * The rtcConfiguration property
     */
    get rtcConfiguration(): RtcConfigurationRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WebRtcRequestBuilderUriTemplate = "{+baseurl}/api/v1/web-rtc";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WebRtcRequestBuilderNavigationMetadata: Record<Exclude<keyof WebRtcRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    rtcConfiguration: {
        requestsMetadata: RtcConfigurationRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
